In [151]:
import pandas as pd
import numpy as np

# pd.set_option("display.max_columns", None)
# pd.set_option("display.max_rows", 20)

In [152]:
# trade_total = pd.read_csv("../data/raw/Trade_total.csv")
trade_total = pd.read_csv("../data/raw/merge-csv.com__6a45176537aa7.csv")
df=trade_total

In [153]:
trade_total=df

In [154]:
trade_total.head()

,typeCode,freqCode,refPeriodId,refYear,refMonth,period,reporterCode,reporterISO,reporterDesc,flowCode,...,netWgt,isNetWgtEstimated,grossWgt,isGrossWgtEstimated,cifvalue,fobvalue,primaryValue,legacyEstimationFlag,isReported,isAggregate
0,C,A,20170101,2017,52,2017,842,USA,USA,X,...,1.274514e+08,False,0,False,0.0,237191006,237191006,0,False,True
1,C,A,20170101,2017,52,2017,842,USA,USA,M,...,4.785700e+04,False,0,False,10386.0,0,10386,0,False,True
2,C,A,20170101,2017,52,2017,842,USA,USA,X,...,1.522223e+09,False,0,False,0.0,353198006,353198006,0,False,True
3,C,A,20170101,2017,52,2017,842,USA,USA,M,...,6.825200e+04,False,0,False,141188.0,0,141188,0,False,True
4,C,A,20170101,2017,52,2017,842,USA,USA,X,...,8.260867e+08,False,0,False,0.0,151883243,151883243,0,False,True

In [155]:
trade_total.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 341 entries, 0 to 340
Data columns (total 47 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   typeCode                  341 non-null    object
 1   freqCode                  341 non-null    object
 2   refPeriodId               341 non-null    int64
 3   refYear                   341 non-null    int64
 4   refMonth                  341 non-null    int64
 5   period                    341 non-null    int64
 6   reporterCode              341 non-null    int64
 7   reporterISO               341 non-null    object
 8   reporterDesc              341 non-null    object
 9   flowCode                  341 non-null    object
 10  flowDesc                  341 non-null    object
 11  partnerCode               341 non-null    int64
 12  partnerISO                341 non-null    object
 13  partnerDesc               341 non-null    object
 14  partner2Code              341 non-null    int64
 15  partner2ISO               341 non-null    object
 16  partner2Desc              341 non-null    object
 17  classificationCode        341 non-null    object
 18  classificationSearchCode  341 non-null    object
 19  isOriginalClassification  341 non-null    bool
 20  cmdCode                   341 non-null    int64
 21  cmdDesc                   341 non-null    object
 22  aggrLevel                 341 non-null    int64
 23  isLeaf                    341 non-null    bool
 24  customsCode               341 non-null    object
 25  customsDesc               341 non-null    object
 26  mosCode                   341 non-null    int64
 27  motCode                   341 non-null    int64
 28  motDesc                   341 non-null    object
 29  qtyUnitCode               341 non-null    int64
 30  qtyUnitAbbr               233 non-null    object
 31  qty                       341 non-null    float64
 32  isQtyEstimated            341 non-null    bool
 33  altQtyUnitCode            341 non-null    int64
 34  altQtyUnitAbbr            88 non-null     object
 35  altQty                    341 non-null    int64
 36  isAltQtyEstimated         341 non-null    bool
 37  netWgt                    339 non-null    float64
 38  isNetWgtEstimated         341 non-null    bool
 39  grossWgt                  341 non-null    int64
 40  isGrossWgtEstimated       341 non-null    bool
 41  cifvalue                  261 non-null    float64
 42  fobvalue                  341 non-null    int64
 43  primaryValue              341 non-null    int64
 44  legacyEstimationFlag      341 non-null    int64
 45  isReported                341 non-null    bool
 46  isAggregate               341 non-null    bool
dtypes: bool(8), float64(3), int64(18), object(18)
memory usage: 106.7+ KB

In [156]:
trade_total.duplicated().sum()

np.int64(0)

In [157]:
trade_total_clean = trade_total[
    [
        "refYear",
        "refMonth",
        "reporterDesc",
        "flowDesc",
        "partnerDesc",
        "cmdCode",
        "cmdDesc",
        "primaryValue",
    ]
]

In [158]:
trade_total_clean.columns = [
    "Year",
    "Month",
    "Reporter",
    "Trade_Flow",
    "Partner",
    "HS_Code",
    "Commodity",
    "Trade_Value_USD",
]

In [159]:
trade_total_clean.head()

,Year,Month,Reporter,Trade_Flow,Partner,HS_Code,Commodity,Trade_Value_USD
0,2017,52,USA,Export,China,203,"Meat of swine; fresh, chilled or frozen",237191006
1,2017,52,USA,Import,China,1001,Wheat and meslin,10386
2,2017,52,USA,Export,China,1001,Wheat and meslin,353198006
3,2017,52,USA,Import,China,1005,Maize (corn),141188
4,2017,52,USA,Export,China,1005,Maize (corn),151883243

In [160]:
trade_total_clean.groupby("HS_Code")["Trade_Value_USD"] \
  .sum() \
  .sort_values(ascending=False) \
  .head(20)

HS_Code
8517    531500631268
8471    418497325556
8708    104976838651
1201    100553049114
8542     94104160699
8528     81136359589
8703     76396919370
8507     73300654757
2709     52248137527
9018     49226394389
8518     41062691512
2711     30874561462
8541     16947967585
1005     13827866958
1007      8932589728
203       5330711974
8505      5014912395
1001      3252466346
2846      2444261617
2805       532941644
Name: Trade_Value_USD, dtype: int64

In [161]:
trade_total.duplicated().sum()

np.int64(0)

In [162]:
trade_total_clean.head()

,Year,Month,Reporter,Trade_Flow,Partner,HS_Code,Commodity,Trade_Value_USD
0,2017,52,USA,Export,China,203,"Meat of swine; fresh, chilled or frozen",237191006
1,2017,52,USA,Import,China,1001,Wheat and meslin,10386
2,2017,52,USA,Export,China,1001,Wheat and meslin,353198006
3,2017,52,USA,Import,China,1005,Maize (corn),141188
4,2017,52,USA,Export,China,1005,Maize (corn),151883243

In [163]:
hs_category = {
    8517: "Telecommunication Equipment",
    8471: "Computers & Data Processing",
    8708: "Vehicle Parts & Accessories",
    1201: "Soybeans",
    8542: "Integrated Circuits (Semiconductors)",
    8528: "Monitors & Television Receivers",
    8703: "Passenger Vehicles",
    8507: "Electric Batteries",
    2709: "Crude Petroleum Oil",
    9018: "Medical & Surgical Instruments",
    8518: "Audio Equipment (Speakers & Microphones)",
    2711: "Petroleum Gases (LNG/LPG)",
    8541: "Semiconductors",
    1005: "Maize (Corn)",
    1007: "Grain Sorghum",
    203: "Pork",
    8505: "Electromagnets & Magnetic Devices",
    1001: "Wheat",
    2846: "Rare-Earth Compounds",
    2805: "Alkali & Alkaline-Earth Metals"
}

trade_total_clean = trade_total_clean.reset_index()

trade_total_clean["Category"] = trade_total_clean["HS_Code"].map(hs_category)

In [164]:
trade_total_clean.head()

,index,Year,Month,Reporter,Trade_Flow,Partner,HS_Code,Commodity,Trade_Value_USD,Category
0,0,2017,52,USA,Export,China,203,"Meat of swine; fresh, chilled or frozen",237191006,Pork
1,1,2017,52,USA,Import,China,1001,Wheat and meslin,10386,Wheat
2,2,2017,52,USA,Export,China,1001,Wheat and meslin,353198006,Wheat
3,3,2017,52,USA,Import,China,1005,Maize (corn),141188,Maize (Corn)
4,4,2017,52,USA,Export,China,1005,Maize (corn),151883243,Maize (Corn)

In [165]:
sector_map = {
    "Telecommunication Equipment": "Technology",
    "Computers & Data Processing": "Technology",
    "Integrated Circuits (Semiconductors)": "Semiconductors",
    "Semiconductors": "Semiconductors",
    "Monitors & Television Receivers": "Electronics",
    "Electric Batteries": "Energy Storage",
    "Audio Equipment (Speakers & Microphones)": "Consumer Electronics",
    "Electromagnets & Magnetic Devices": "Industrial Equipment",

    "Passenger Vehicles": "Automobile",
    "Vehicle Parts & Accessories": "Automobile",

    "Medical & Surgical Instruments": "Healthcare",

    "Crude Petroleum Oil": "Energy",
    "Petroleum Gases (LNG/LPG)": "Energy",

    "Soybeans": "Agriculture",
    "Maize (Corn)": "Agriculture",
    "Grain Sorghum": "Agriculture",
    "Pork": "Agriculture",
    "Wheat": "Agriculture",

    "Rare-Earth Compounds": "Critical Minerals",
    "Alkali & Alkaline-Earth Metals": "Chemicals"
}

trade_total_clean["Sector"] = trade_total_clean["Category"].map(sector_map)

In [166]:
sector_trade = (
    trade_total_clean
    .groupby("Sector")["Trade_Value_USD"]
    .sum()
    .sort_values(ascending=False)
)

print(sector_trade)

Sector
Technology              949997956824
Automobile              181373758021
Agriculture             131896684120
Semiconductors          111052128284
Energy                   83122698989
Electronics              81136359589
Energy Storage           73300654757
Healthcare               49226394389
Consumer Electronics     41062691512
Industrial Equipment      5014912395
Critical Minerals         2444261617
Chemicals                  532941644
Name: Trade_Value_USD, dtype: int64

In [167]:
df["primaryValue"].sum()

np.int64(1710161442141)

In [168]:
df.groupby("refYear")["primaryValue"].sum()

refYear
2017    204032293084
2018    197566279939
2019    175020461424
2020    190656225846
2021    226318795770
2022    228977782797
2023    197302511637
2024    187457744806
2025    102829346838
Name: primaryValue, dtype: int64

In [169]:
tariff_map = {

    # ===================== Technology =====================
    **{(y, "Telecommunication Equipment"): (0 if y == 2017 else 25) for y in range(2017, 2026)},
    **{(y, "Computers & Data Processing"): (0 if y == 2017 else 25) for y in range(2017, 2026)},
    **{(y, "Integrated Circuits (Semiconductors)"): (0 if y == 2017 else (50 if y >= 2024 else 25)) for y in range(2017, 2026)},
    **{(y, "Semiconductors"): (0 if y == 2017 else (50 if y >= 2024 else 25)) for y in range(2017, 2026)},
    **{(y, "Monitors & Television Receivers"): (0 if y == 2017 else 25) for y in range(2017, 2026)},
    **{(y, "Audio Equipment (Speakers & Microphones)"): (0 if y == 2017 else 25) for y in range(2017, 2026)},

    # ===================== Automobile =====================
    **{(y, "Passenger Vehicles"): (2.5 if y < 2024 else 100) for y in range(2017, 2026)},
    **{(y, "Vehicle Parts & Accessories"): (2.5 if y == 2017 else (25 if y < 2024 else 25)) for y in range(2017, 2026)},

    # ===================== Energy =====================
    **{(y, "Electric Batteries"): (0 if y < 2024 else 25) for y in range(2017, 2026)},
    **{(y, "Crude Petroleum Oil"): 0 for y in range(2017, 2026)},
    **{(y, "Petroleum Gases (LNG/LPG)"): (0 if y == 2017 else 25) for y in range(2017, 2026)},

    # ===================== Agriculture =====================
    **{(y, "Soybeans"): (0 if y == 2017 else 25) for y in range(2017, 2026)},
    **{(y, "Maize (Corn)"): (0 if y == 2017 else 25) for y in range(2017, 2026)},
    **{(y, "Grain Sorghum"): (0 if y == 2017 else 25) for y in range(2017, 2026)},
    **{(y, "Pork"): (0 if y == 2017 else 25) for y in range(2017, 2026)},
    **{(y, "Wheat"): (0 if y == 2017 else 25) for y in range(2017, 2026)},

    # ===================== Healthcare =====================
    **{(y, "Medical & Surgical Instruments"): (0 if y == 2017 else 25) for y in range(2017, 2026)},

    # ===================== Critical Minerals =====================
    **{(y, "Rare-Earth Compounds"): (0 if y == 2017 else 25) for y in range(2017, 2026)},
    **{(y, "Alkali & Alkaline-Earth Metals"): (0 if y == 2017 else 25) for y in range(2017, 2026)},

    # ===================== Industrial =====================
    **{(y, "Electromagnets & Magnetic Devices"): (0 if y == 2017 else 25) for y in range(2017, 2026)},
}

trade_total_clean["Tariff_Rate (%)"] = trade_total_clean.apply(
    lambda row: tariff_map.get((row["Year"], row["Category"]), 0),
    axis=1
)

In [174]:
trade_total_clean.insert(0, "level_0", range(len(trade_total_clean)))

In [175]:
trade_total_clean.to_csv("../data/clean/trade_total_clean.csv", index=False)

In [171]:
sector_year = (
    trade_total_clean
    .groupby(["Year", "Sector"])["Trade_Value_USD"]
    .sum()
    .reset_index()
)

sector_year.head()

   Year                Sector  Trade_Value_USD
0  2017           Agriculture      13816508942
1  2017            Automobile      24384696289
2  2017             Chemicals         54034581
3  2017  Consumer Electronics       3322232917
4  2017     Critical Minerals         79438596

In [172]:
sector_pivot = sector_year.pivot(
    index="Sector",
    columns="Year",
    values="Trade_Value_USD"
)

sector_pivot

Year,2017,2018,2019,2020,2021,2022,2023,2024,2025
Sector,,,,,,,,,
Agriculture,13816508942,4016341289,9149874880,18782845036,22761292071,25881785202,18791062015,15261821239,3435153446
Automobile,24384696289,23113106391,20170731340,17834919622,20748358521,21208247753,20194456274,20160089854,13559151977
Chemicals,54034581,84677884,45332611,34511601,41606381,77589493,81620946,71191184,42376963
Consumer Electronics,3322232917,3698469158,3581442358,4243255731,5842511850,6352506017,5450032669,5645525222,2926715590
Critical Minerals,79438596,160090832,153573615,144581342,353414652,638586209,429702749,307241129,177632493
Electronics,11744977752,12782046041,11580793654,8359670794,9671719274,9629685882,6854646446,7036792218,3476027528
Energy,6739369391,7071812653,3063242956,9203013249,12074631036,10973972229,17625809724,12351409692,4019438059
Energy Storage,1854360490,2390017387,2476556475,2867103996,5520556291,11014189300,15927149869,18217105952,13033614997
Healthcare,4100310452,4529063215,4985333736,5420554698,6158151381,6433971083,5895482028,5852502097,5851025699
Industrial Equipment,459155686,525605556,478212377,407977231,590610996,785301974,662355731,584366399,521326445
Semiconductors,10796390020,11526164371,11474209613,13913044924,16406745277,13932428718,8577160601,11894181864,12531802896
Technology,126680817968,127668885162,107861157809,109444747622,126149198040,122049518937,96813032585,90075517956,43255080745

In [173]:
sector_pivot["Impact (%)"] = (
    (sector_pivot["Year"] - sector_pivot[2017])
    / sector_pivot[2017]
) * 100

KeyError: 'Year'